---
sidebar: sidebar
permalink: fg-space-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: fg.space events
---

= fg.space events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== fg.space.member.allOK
*Severity*::
NOTICE
*Description*::
This message occurs when conditions that led to previous "fg.space.member.nearlyFull" and "fg.space.member.full" events no longer apply. All constituents within this FlexGroup have sufficient space for normal operation.
*Corrective Action*::
(None).
*Syslog Message*::
The FlexGroup %s (fg-uuid %s) no longer has any full constituents.
*Parameters*::
*object_name* (STRING): Human-readable name of the FlexGroup.
*object_uuid* (STRING): UUID of the FlexGroup.

== fg.space.member.full
*Severity*::
ALERT
*Description*::
This message occurs when a constituent within a FlexGroup is now full. Although new files can still be created within the FlexGroup and some files can still be expanded, none of the files that are stored on this constituent can be modified. The user might see random out-of-space errors as a consequence when trying to perform write operations on this FlexGroup.
*Corrective Action*::
Adding capacity to the FlexGroup by using the "volume modify -size +X" command is the best way to solve this problem. Alternatively, deleting files from the FlexGroup might work, but it is difficult to determine which files have landed on which constituent.
*Syslog Message*::
Constituent %llu in FlexGroup %s (fg-uuid %s) is out of space.
*Parameters*::
*constituent_dsid* (LONGINT): DSID of the constituent that is out of space.
*object_name* (STRING): Human-readable name of the FlexGroup.
*object_uuid* (STRING): UUID of the FlexGroup.

== fg.space.member.nearlyFull
*Severity*::
ALERT
*Description*::
This message occurs when a constituent within a FlexGroup is nearly out of space. Although files can be created and expanded, if the constituent runs out of space entirely, the user's ability to append to and modify those files that reside on this constituent will be impeded.
*Corrective Action*::
Adding capacity to the FlexGroup by using the "volume modify -size +X" command is the best way to solve this problem. Alternatively, deleting files from the FlexGroup might work, but it is difficult to determine which files have landed on which constituent.
*Syslog Message*::
Constituent %llu in FlexGroup %s (fg-uuid %s) is nearly out of space.
*Parameters*::
*constituent_dsid* (LONGINT): DSID of the constituent that is nearly out of space.
*object_name* (STRING): Human-readable name of the FlexGroup.
*object_uuid* (STRING): UUID of the FlexGroup.
