---
sidebar: sidebar
permalink: nblade-fpolicy-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: nblade.fpolicy events
---

= nblade.fpolicy events
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== nblade.fpolicy.extn.failed
*Severity*::
EMERGENCY
*Description*::
This message occurs when an I/O operation directed at a FlexCache(R) volume fails because the file extension include and exclude list of one of the policies is too long to send to the origin of the FlexCache volume.
*Corrective Action*::
Decrease the number of file extensions configured in the include and exclude list in the FPolicy scope by using the "fpolicy policy scope modify" command.
*Syslog Message*::
FPolicy processing failed on volume MSID "%lu", for Vserver ID "%lu", policy ID "%lu", as the combined length for the file extension include and exclude list is greater than %llu. Decrease the number of file extensions configured.
*Parameters*::
*msid* (LONGINT): MSID of FlexCache volume.
*vserverid* (LONGINT): ID of the Vserver.
*policyid* (LONGINT): ID of the FPolicy.
*maxmimumListLengthAllowed* (LONGINT): Maximum length that can be sent to the origin volume.

== nblade.fpolicy.policy.skip
*Severity*::
EMERGENCY
*Description*::
This message occurs when a non-mandatory FPolicy(tm) policy check is skipped while processing an I/O on the FlexCache(R) volume because the file extension include and exclude list of the policy is too long to send to the origin volume of the FlexCache volume. The error does not fail the operation and other policies, if any, are matched.
*Corrective Action*::
Decrease the number of file extensions configured in the include and exclude list in the FPolicy scope by using the "fpolicy policy scope modify" command.
*Syslog Message*::
FPolicy check is skipped for a non-mandatory policy ID "%lu" on volume MSID "%lu" for Vserver ID "%lu" because the combined length for the file extension include and exclude list is greater than %llu.
*Parameters*::
*policyid* (LONGINT): ID of the FPolicy policy.
*msid* (LONGINT): MSID of the FlexCache volume.
*vserverid* (LONGINT): ID of the Vserver.
*maximumListLengthAllowed* (LONGINT): Maximum length that can be sent to the origin volume.
