---
sidebar: sidebar
permalink: san-duplicateipaddress-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: san.duplicateipaddress events
---

= san.duplicateipaddress events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== san.DuplicateIpAddress
*Severity*::
ERROR
*Description*::
This message occurs in MetroCluster(tm) configurations of clustered Data ONTAP(R), when an iSCSI LIF is created in the source cluster, but one of the Vservers in the destination cluster is already configured with an iSCSI LIF having the same IP address.
*Corrective Action*::
Provide a unique IP address for the primary Vserver iSCSI LIF when creating or modifying the LIF in the source cluster. After modifying the IP address, check that Vserver configuration-state is healthy by using the "metrocluster vserver show -vserver <vserver>" command. If Vserver configuration-state is not healthy, resynchronize the Vserver with its partner by using the "metrocluster vserver resync" command.
*Syslog Message*::
One of the Vservers in the destination cluster is configured with an iSCSI LIF with the same IP address %s. Provide a different unique IP address for the primary Vserver iSCSI LIF %s when creating or modifying the LIF in the source cluster.
*Parameters*::
*IpAddress* (STRING): IP address existing in the destination cluster.
*lif* (STRING): Name of the primary Vserver iSCSI LIF.
