---
sidebar: sidebar
permalink: scsiblade-san-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: scsiblade.san events
---

= scsiblade.san events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== scsiblade.san.config.active
*Severity*::
NOTICE
*Description*::
This message occurs when the SAN active-active state has changed.
*Corrective Action*::
(None).
*Syslog Message*::
The symmetric active-active state is %s on %lld LUNs.
*Parameters*::
*state* (STRING): Active-active state.
*num_luns* (INT): Number of LUNs.

== scsiblade.san.ssm.lu.degraded
*Severity*::
ALERT
*Description*::
This message occurs when a LUN is marked as degraded due to a SnapMirror(R) Automated Failover relationship going out of sync. The LUN is no longer accessible from the host.
*Corrective Action*::
Restore LUN access to the host by using the "snapmirror resync" command to bring the out-of-sync relationship back in sync. For assistance, contact NetApp Support.
*Syslog Message*::
LUN %s was marked as degraded due to a SnapMirror Automated Failover relationship going out of sync.
*Parameters*::
*LUNSerialNumber* (STRING): Serial number of the LUN.

== scsiblade.san.ssm.lu.online
*Severity*::
NOTICE
*Description*::
This message occurs when a LUN is back online and might be accessible again from the host.
*Corrective Action*::
If the host still can't access the LUN even though the LUN is back online, perform a host-side rescan operation or a reboot to enable the host to access the LUN.
*Syslog Message*::
LUN %s is back online.
*Parameters*::
*LUNSerialNumber* (STRING): Serial number of the LUN.
